---
- hosts: bridgewalker
  user: jan
  gather_facts: no
  vars:
    home: /home/jan
  tasks:
  - name: install additional Ansible dependencies
    command: /usr/bin/aptitude -y install python-apt
                creates=/usr/share/doc/python-apt
    sudo: yes

  - name: install Debian packages
    apt: pkg=$item state=present
    with_items:
      - screen
      - htop
      - openjdk-6-jre-headless       # MtGoxCachingProxy seems to have
                                     # problems with Java 7
      - supervisor
      - postgresql
      - python-psycopg2
      - haskell-platform
      - rsync
      - backupninja
      - python-paramiko
      - libcurl4-gnutls-dev
      - librsync1                    # dependency for duplicity
      - libboost-system1.49.0               # \
      - libboost-filesystem1.49.0           # > for Bitcoin daemon
      - libboost-program-options1.49.0      # |
      - libboost-thread1.49.0               # |
      - libdb5.1++                          # /
    sudo: yes

  - name: install Haskell development packages
    apt: pkg=$item state=present
    with_items:
      - libghc-aeson-dev
      - libghc-attoparsec-dev
      - libghc-base16-bytestring-dev
      - libghc-base64-bytestring-dev
      - libghc-cereal-dev
      - libghc-configfile-dev
      - libghc-curl-dev
      - libghc-hashable-dev
      - libghc-http-dev
      - libghc-ixset-dev
      - libghc-monadcatchio-transformers-dev
      - libghc-mtl-dev
      - libghc-network-dev
      - libghc-postgresql-simple-dev
      - libghc-pwstore-fast-dev
      - libghc-random-dev
      - libghc-regex-compat-dev
      - libghc-sha-dev
      - libghc-test-framework-hunit-dev
      - libghc-test-framework-quickcheck2-dev
      - libghc-text-dev
      - libghc-transformers-dev
      - libghc-unordered-containers-dev
      - libghc-vector-dev
    sudo: yes
    when: is_staging is defined

  - name: install additional Haskell development packages via Cabal
    shell: cabal update;
           cd /home/jan/src/watchdog; cabal install;
           cd /home/jan/src/bitcoin-rpc; cabal install;
           cd /home/jan/src/mtgoxapi; cabal install;
           cd /home/jan/src/metricsd-client; cabal install;
           cd /home/jan/src/bridgewalker; cabal install;
    when: update_cabal == "yes"

  - name: create link to Bridgewalker source code
    file: src=$home/src/bridgewalker
          dest=$home/bridgewalker
          state=link
    when: is_staging is defined

  - name: create folder for MtGoxCachingProxy
    file: path=$home/MtGoxCachingProxy
          state=directory

  - name: install MtGoxCachingProxy
    copy: src=../MtGoxCachingProxy/dist/MtGoxCachingProxy.jar
          dest=$home/MtGoxCachingProxy/MtGoxCachingProxy.jar
    notify: restart mtgoxcachingproxy

  - name: add supervisor configuration for MtGoxCachingProxy
    copy: src=files/etc/supervisor/conf.d/mtgoxcachingproxy.conf
          dest=/etc/supervisor/conf.d/mtgoxcachingproxy.conf
          owner=root
          group=root
    sudo: yes
    notify: update supervisor

  - name: create Bitcoin daemon configuration directory
    file: path=$home/.bitcoin
          state=directory
    when: is_production is defined

  - name: configure Bitcoin daemon
    copy: src=files/home/jan/bitcoin/bitcoin.conf
          dest=$home/.bitcoin/bitcoin.conf
    when: is_production is defined

  - name: create folder for Bitcoin daemon
    file: path=$home/bitcoind
          state=directory

  - name: install custom Bitcoin daemon
    copy: src=../../../../repos/bitcoin-bw-production/src/bitcoind
          dest=$home/bitcoind/bitcoind
    when: is_production is defined

  - name: install custom Bitcoin daemon (staging)
    copy: src=../../../../repos/bitcoin-bw-staging/src/bitcoind
          dest=$home/bitcoind/bitcoind
    when: is_staging is defined

  - name: add supervisor configuration for Bitcoin daemon
    copy: src=files/etc/supervisor/conf.d/bitcoind.conf
          dest=/etc/supervisor/conf.d/bitcoind.conf
          owner=root
          group=root
    sudo: yes
    notify: update supervisor
    when: is_production is defined

  - name: add supervisor configuration for Bitcoin daemon (staging)
    copy: src=files/etc/supervisor/conf.d/bitcoind.conf_staging
          dest=/etc/supervisor/conf.d/bitcoind.conf
          owner=root
          group=root
    sudo: yes
    notify: update supervisor
    when: is_staging is defined

  - name: install pidnotifier
    copy: src=../../one-off/PidNotifier/PidNotifier
          dest=$home/.bitcoin/pidnotifier
    when: is_production is defined

  - name: add Debian backports repository
    copy: src=files/etc/apt/sources.list.d/backports.list
          dest=/etc/apt/sources.list.d/backports.list
          owner=root
          group=root
          mode=644
    sudo: yes

  - name: update aptitude   # need to run right away, otherwise the next
                            # task will fail
    shell: /usr/bin/aptitude update;
            touch /root/.ansible_marker_backports_repository_included
            creates=/root/.ansible_marker_backports_repository_included
    sudo: yes

  - name: install backported nginx  # need at least 1.3.13 for websocket support
    apt: pkg=nginx default_release=wheezy-backports state=present
    sudo: yes

  - name: add nginx configuration for bridgewalker
    copy: src=files/etc/nginx/sites-available/bridgewalker
          dest=/etc/nginx/sites-available/bridgewalker
          owner=root
          group=root
          mode=600
    sudo: yes
    notify: restart nginx
    when: is_production is defined

  - name: add nginx configuration for bridgewalker (staging)
    copy: src=files/etc/nginx/sites-available/bridgewalker_staging
          dest=/etc/nginx/sites-available/bridgewalker
          owner=root
          group=root
          mode=600
    sudo: yes
    notify: restart nginx
    when: is_staging is defined

  - name: create folder for SSL files
    file: path=/etc/nginx/certs
          state=directory
          owner=www-data
          group=www-data
          mode=700
    sudo: yes
    notify: restart nginx

  - name: add SSL files for bridgewalker
    copy: src=files/etc/nginx/certs/$item
          dest=/etc/nginx/certs/$item
          owner=www-data
          group=www-data
    with_items:
      - bridgewalker-unified.crt
      - bridgewalker_encrypted.key
      - NOTES
    sudo: yes
    notify: restart nginx
    when: is_production is defined

  - name: check whether the SSL key has been decrypted
    file: path=/etc/nginx/certs/bridgewalker.key
          state=file
    sudo: yes
    ignore_errors: True
    register: ssl_key_decrypted
    when: is_production is defined

  - name: tell user to decrypt SSL key
    pause: prompt="Please decrypt the SSL key in /etc/nginx/certs."
    when: ssl_key_decrypted|failed
    notify: restart nginx
    # can only happen when $is_production is set

  - name: ensure that the SSL key has been decrypted
    file: path=/etc/nginx/certs/bridgewalker.key
          state=file
          owner=www-data
          group=www-data
          mode=600
    sudo: yes
    notify: restart nginx
    when: is_production is defined

  - name: create self-signed SSL cert
    command: openssl req -new -nodes -x509 -subj "/CN=${bridgewalker_fqdn}"
                -days 3650 -keyout /etc/nginx/certs/bridgewalker.key
                -out /etc/nginx/certs/bridgewalker-unified.crt -extensions v3_ca
                creates=/etc/nginx/certs/bridgewalker-unified.crt
    sudo: yes
    notify: restart nginx
    when: is_staging is defined

  - name: ensure that SSL cert is owned by www-data
    file: path=$item
          state=file
          owner=www-data
          group=www-data
          mode=600
    with_items:
      - /etc/nginx/certs/bridgewalker-unified.crt
      - /etc/nginx/certs/bridgewalker.key
    sudo: yes
    notify: restart nginx
    when: is_staging is defined

  - name: disable default nginx configuration
    file: path=/etc/nginx/sites-enabled/default
          state=absent
    sudo: yes
    notify: restart nginx

  - name: enable nginx configuration for bridgewalker
    file: src=/etc/nginx/sites-available/bridgewalker
          dest=/etc/nginx/sites-enabled/bridgewalker
          state=link
    sudo: yes
    notify: restart nginx

    # TODO: sudo_user does not seem to work when running against Vagrant VM
  - name: create database for Bridgewalker
    postgresql_db: name=bridgewalker
    sudo_user: postgres
    sudo: yes
    when: is_production is defined

  - name: give user jan access to database
    shell: /usr/bin/createuser --no-createdb --no-createrole --no-superuser jan;
           touch /var/lib/postgresql/.ansible_marker_user_jan_created
           creates=/var/lib/postgresql/.ansible_marker_user_jan_created
    sudo_user: postgres
    sudo: yes
    when: is_production is defined

  - name: create folder for metricsd
    file: path=$home/metricsd
          state=directory

  - name: download metricsd
    command: /usr/bin/wget https://github.com/downloads/mojodna/metricsd/metricsd-0.4.2-jar-with-dependencies.jar
                -O $home/metricsd/metricsd-0.4.2-jar-with-dependencies.jar
                creates=$home/metricsd/metricsd-0.4.2-jar-with-dependencies.jar
    notify: restart metricsd

  - name: add configuration for metricsd
    copy: src=files/home/jan/metricsd/config.json
          dest=/home/jan/metricsd/config.json
    notify: restart metricsd

  - name: add supervisor configuration for metricsd
    copy: src=files/etc/supervisor/conf.d/metricsd.conf
          dest=/etc/supervisor/conf.d/metricsd.conf
          owner=root
          group=root
    sudo: yes
    notify: update supervisor

  - name: create folder for Bridgewalker configuration
    file: path=$home/.bridgewalker
          state=directory

  - name: add Bridgewalker configuration
    copy: src=files/home/jan/bridgewalker/$item
          dest=/home/jan/.bridgewalker/$item
    with_items:
      - config_template
      - workingfund
    when: is_production is defined

  - name: add Bridgewalker configuration (staging)
    copy: src=files/home/jan/bridgewalker/${item}_staging
          dest=/home/jan/.bridgewalker/$item
    with_items:
      - config_template
      - workingfund
    when: is_staging is defined

  - name: add supervisor configuration for Bridgewalker
    copy: src=files/etc/supervisor/conf.d/bridgewalker.conf
          dest=/etc/supervisor/conf.d/bridgewalker.conf
          owner=root
          group=root
    sudo: yes
    notify: update supervisor
    when: is_production is defined

  - name: create folders for Bridgewalker
    file: path=$home/$item
          state=directory
    with_items:
      - bridgewalker
      - bridgewalker/log
    when: is_production is defined

  - name: copy Bridgewalker assets (snaplets)
    local_action: command rsync -a
                        ../bridgewalker/snaplets
                        $bridgewalker_fqdn:$home/bridgewalker
    when: is_production is defined

  - name: copy Bridgewalker assets (static)
    local_action: command rsync -a
                        ../bridgewalker/static
                        $bridgewalker_fqdn:$home/bridgewalker
    when: is_production is defined

  - name: copy Bridgewalker binary
    copy: src=../../../../.cabal/bin/bridgewalker
          dest=$home/bridgewalker/bridgewalker
    notify: restart bridgewalker
    when: is_production is defined

  - name: download newer version of duplicity  # need something like 0.6.21,
                                               # as older versions seem to
                                               # have buggy SSH support
    command: /usr/bin/wget http://ftp.de.debian.org/debian/pool/main/d/duplicity/duplicity_0.6.22-1_$arch.deb
                -O /root/duplicity_0.6.22-1_$arch.deb
                creates=/root/duplicity_0.6.22-1_$arch.deb
    sudo: yes

  - name: install newer version of duplicity
    command: dpkg -i /root/duplicity_0.6.22-1_$arch.deb
             creates=/usr/bin/duplicity
    sudo: yes

  - name: add backupninja configuration
    copy: src=files/etc/backupninja.conf
          dest=/etc/backupninja.conf
          owner=root
          group=root
    sudo: yes

  - name: create folders for backupninja
    file: path={{item.path}}
          state=directory
          owner={{item.user}}
          group={{item.user}}
    with_items:
      - { path: '/etc/backup.d/template', user: 'root' }
      - { path: '/var/backups/backupninja', user: 'root' }
      - { path: '/var/backups/backupninja/bitcoind', user: 'jan' }
    sudo: yes

  - name: copy backupninja backup scripts
    copy: src=files/etc/backup.d/{{item.file}}
          dest=/etc/backup.d/{{item.file}}
          owner=root
          group=root
          mode={{item.mode}}
    with_items:
     - { file: '10-bitcoind.sh', mode: 700 }
     - { file: '20-postgresql.pgsql', mode: 600 }
     - { file: 'template/90-off-site.dup', mode: 600 }
    sudo: yes

  - name: check whether the backupninja passphrase has been configured
    file: path=/etc/backup.d/90-off-site.dup
          state=file
    sudo: yes
    ignore_errors: True
    register: backupninja_passphrase
    when: is_production is defined

  - name: tell user to configure the backupninja passphrase
    pause: prompt="Please create /etc/backup.d/90-off-site.dup and insert the backupninja passphrase."
    when: backupninja_passphrase|failed
    # can only happen when $is_production is set

  - name: ensure that the backupninja passphrase has been configured
    file: path=/etc/backup.d/90-off-site.dup
          state=file
          owner=root
          group=root
          mode=600
    sudo: yes
    when: is_production is defined

  - name: create folder for backup ssh keys
    file: path=/root/.ssh
          state=directory
          owner=root
          group=root
          mode=700
    sudo: yes

  - name: copy ssh keys for backup login
    copy: src=files/root/ssh/$item
          dest=/root/.ssh/$item
          owner=root
          group=root
          mode=600
    with_items:
      - id_dsa.gpg
      - id_dsa.pub
      - NOTES
    sudo: yes

  - name: check whether backup ssh key has been decrypted
    file: path=/root/.ssh/id_dsa
          state=file
    sudo: yes
    ignore_errors: True
    register: backup_ssh_key
    when: is_production is defined

  - name: tell user to decrypt the backup ssh key
    pause: prompt="Please decrypt the file /root/.ssh/id_dsa.gpg (use backupninja passphrase)."
    when: backup_ssh_key|failed
    # can only happen when $is_production is set

  - name: ensure that the backup ssh key has been decrypted
    file: path=/root/.ssh/id_dsa
          state=file
          owner=root
          group=root
          mode=600
    sudo: yes
    when: is_production is defined

  handlers:
  - name: update supervisor
    command: /usr/bin/supervisorctl update
    sudo: yes

  - name: restart mtgoxcachingproxy
    command: /usr/bin/supervisorctl restart mtgoxcachingproxy
    sudo: yes

  - name: restart bridgewalker
    command: /usr/bin/supervisorctl restart bridgewalker
    sudo: yes

  - name: restart metricsd
    command: /usr/bin/supervisorctl restart metricsd
    sudo: yes

  - name: restart nginx
    service: name=nginx state=restarted
    sudo: yes
