---
- hosts: bridgewalker
  user: jan
  gather_facts: no
  vars:
    home: /home/jan
  tasks:
  - name: install additional Ansible dependencies
    command: /usr/bin/aptitude -y install python-apt
                creates=/usr/share/doc/python-apt
    sudo: yes

  - name: install Debian packages
    apt: pkg=$item state=present
    with_items:
      - screen
      - htop
      - openjdk-6-jre-headless       # MtGoxCachingProxy seems to have
                                     # problems with Java 7
      - supervisor
    sudo: yes

  - name: create folders for MtGoxCachingProxy
    file: path=$home/$item
          state=directory
    with_items:
      - MtGoxCachingProxy
      - MtGoxCachingProxy/lib

  - name: install MtGoxCachingProxy
    copy: src=../MtGoxCachingProxy/dist/$item
          dest=$home/MtGoxCachingProxy/$item
    with_items:
      - MtGoxCachingProxy.jar
      - lib/socketio.jar
    notify: restart mtgoxcachingproxy

  - name: add supervisor configuration for MtGoxCachingProxy
    copy: src=files/etc/supervisor/conf.d/mtgoxcachingproxy.conf
          dest=/etc/supervisor/conf.d/mtgoxcachingproxy.conf
          owner=root
          group=root
    sudo: yes
    notify: update supervisor

  - name: create Bitcoin daemon configuration directory
    file: path=$home/.bitcoin
          state=directory

  - name: install pidnotifier
    copy: src=../../one-off/PidNotifier/PidNotifier
          dest=$home/.bitcoin/pidnotifier

  - name: add Debian backports repository
    copy: src=files/etc/apt/sources.list.d/backports.list
          dest=/etc/apt/sources.list.d/backports.list
          owner=root
          group=root
    sudo: yes
    notify: update aptitude

  - name: install backported nginx  # need at least 1.3.13 for websocket support
    apt: pkg=nginx default_release=wheezy-backports state=present
    sudo: yes

  handlers:
  - name: update supervisor
    command: /usr/bin/supervisorctl update
    sudo: yes

  - name: restart mtgoxcachingproxy
    command: /usr/bin/supervisorctl restart mtgoxcachingproxy
    sudo: yes

  - name: update aptitude
    command: /usr/bin/aptitude update
    sudo: yes
